apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: viken-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-mapping-service_viken_no
  fintlabs.no/org-id: viken.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "viken-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "viken.no"
    target:
      kind: Application
      name: fint-flyt-mapping-service

