apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rogfk-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-mapping-service_rogfk_no
      fintlabs.no/org-id: rogfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "rogfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "rogfk.no"
      - op: add
        path: "/spec/env/-"
        value:
          name: "novari.kafka.topic.orgId"
          value: "rogfk-no"
    target:
      kind: Application
      name: fint-flyt-mapping-service
